### ISSUE TITLE
FEATURE REQ: weekly instead of daily jobs

### ISSUE THREAD

**Issue by klukose3** [CharliePalm/NotionHabitsIntegration#1]
Would it be possible to add all my habits for the week to the planner instead of just today? That way I don't have to pull up the cmd prompt every day to add my habits.

**Comment by CharliePalm** [comment]
There may be an issue with the "created" property but it's possible I could find a workaround. Alternatively you can have your operating system carry this out every day in the meantime: 

https://stackoverflow.com/questions/1683620/getting-started-with-cronjobs-on-a-mac
https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10

I'll look into seeing if it would be simple enough to change things to a weekly basis, though. Thanks for the suggestion!

**Comment by CharliePalm** [comment]
This is done, re-init your config and select weekly, monthly, or cycle to cycle as your schedule. happy habit-ing!
